name: Animation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '30 10 * * 5'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup tools
        run: |
         curl -L https://github.com/mnyoshie.gpg | gpg --import
         cd scripts && ./setup-linux.sh

      - name: Retrieve cuts
        run: cd scripts && ./retrieve.sh

      - name: Flatten cuts
        run: cd scripts && ./flatten.sh

      - name: Compile cuts
        run: cd scripts && ./compile.sh

      - name: Prepare upload
        run: |
         cd scripts && source config.sh
         echo "ARTIFACT_NAME=$ANIMATION_CODENAME-$(date -I)" >> $GITHUB_ENV

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./flattened/${{ env.ARTIFACT_NAME }}.mp4

